trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: 'Build'
  jobs:
    - job: 'Buildmttdemoapplication'
      steps:
      - task: NuGetToolInstaller@1
        displayName: 'Install Nuget' 

      - task: NuGetCommand@2
        displayName: 'RestoreNuget'
        inputs:
          restoreSolution: '$(solution)'
      
      - task: VSBuild@1
        displayName: 'MsBuild and set VS version'
        inputs:
          solution: '$(solution)'
          msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: VSTest@2
        displayName: 'VStest'
        inputs:
          platform: '$(buildPlatform)'
          configuration: '$(buildConfiguration)'

      - task: PublishPipelineArtifact@0
        displayName: 'Publish pipeline artifacts'
        inputs:
          targetPath: $(Build.ArtifactStagingDirectory)
          artifactName: 'Webapp'


- stage: Deploy
  displayName: Deployment
  dependsOn: Build
  condition: succeeded()
  jobs: 
  - deployment: DeployMTTWebapp
    displayName: 'Deploy'
    environment: 'stage'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadPipelineArtifact@2
            displayName: 'Download Pipeline Artifact'
            inputs:
              artifactName: 'Webapp'
              targetPath: $(System.ArtifactsDirectory)
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure app service'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'mttdemo'
              appType: 'webApp'
              WebAppName: 'mttdemo'
              packageForLinux: '$(System.ArtifactsDirectory)/*.zip'

